Feature: Added new badge component
poojakelkar/ng-component-library pull request #4
Opened 2022-02-07 12:34 UTC by poojakelkar

- Added badge with the image
- Added Online Badge

2022-02-08 15:25 UTC, haarsh24 requested changes

2022-02-08 15:25 UTC, haarsh24 commented on components/badge/badgeStyle.css
> +}
Declare the colors and then use it .

2022-02-08 15:25 UTC, haarsh24 commented on components/badge/badgeStyle.css
>      padding: 4px 8px;
Declare values in rem or em instead of px , so it will be convenient when you add responsiveness to website

2022-02-08 15:25 UTC, haarsh24 commented on components/badge/badgeStyle.css
> +}
Declare these color values

2022-02-08 15:25 UTC, haarsh24 commented on components/badge/badgeStyle.css
> +
Use same color codes everywhere

2022-02-08 15:25 UTC, haarsh24 commented on components/badge/badgeStyle.css
>  }
Suggestion: Use (2rem/2px) instead of using medium/large.

2022-02-09 13:48 UTC, merged

2022-02-09 13:51 UTC, shobit1337 commented
Looks good to me!

2022-02-09 13:58 UTC, shobit1337 reviewed
Looks good to me! Approved.